name: Deploy Docker Project
on:
  push:
    branches:
      - main
    paths:
      - 'project-docker/**'
      - '.github/workflows/deploy-docker.yaml'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dev/docker-react -f ./project-docker/Dockerfile.dev ./project-docker
      - run: docker run -e CI=true dev/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker
          environment_name: Docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-279844085188
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip