name: Deploy Complex Project
on:
  push:
    branches:
      - main
    paths:
      - 'complex/**'
      - '.github/workflows/deploy-complex.yaml'

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t devaprakash/react-test -f ./complex/client/Dockerfile.dev ./complex/client
      - run: docker run -e CI=true devaprakash/react-test npm test
      
  build:
    needs: test-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t devaprakash/multi-client ./complex/client
      - run: docker build -t devaprakash/multi-nginx ./complex/nginx
      - run: docker build -t devaprakash/multi-server ./complex/server
      - run: docker build -t devaprakash/multi-worker ./complex/worker
      - run: docker push devaprakash/multi-client
      - run: docker push devaprakash/multi-nginx
      - run: docker push devaprakash/multi-server
      - run: docker push devaprakash/multi-worker
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: einaregilsson/beanstalk-deploy@v18
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-279844085188
          region: us-east-1
          version_label: ${{ github.sha }}
