name: Deploy Complex Project
on:
  push:
    branches:
      - main
    paths:
      - 'complex/**'
      - '.github/workflows/deploy-complex.yaml'

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t dev/react-test -f ./complex/client/Dockerfile.dev ./complex/client
      - run: docker run -e CI=true dev/react-test npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t devaprakash/multi-client ./complex/client
      - run: docker build -t devaprakash/multi-nginx ./complex/nginx
      - run: docker build -t devaprakash/multi-server ./complex/server
      - run: docker build -t devaprakash/multi-worker ./complex/worker
      - run: docker push devaprakash/multi-client
      - run: docker push devaprakash/multi-nginx
      - run: docker push devaprakash/multi-server
      - run: docker push devaprakash/multi-worker
