name: Deploy Complex Project
on:
  push:
    branches:
      - main
    paths:
      - 'complex/**'
      - '.github/workflows/deploy-complex.yaml'

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t devaprakash/react-test -f ./complex/client/Dockerfile.dev ./complex/client
      - run: docker run -e CI=true devaprakash/react-test npm test
      - run: docker build -t devaprakash/multi-client -f ./complex/client/Dockerfile ./complex/client
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t devaprakash/multi-client -f ./complex/client/Dockerfile ./complex/client
      - run: docker build -t devaprakash/multi-nginx ./complex/nginx/Dockerfile ./complex/nginx
      - run: docker build -t devaprakash/multi-server ./complex/server/Dockerfile ./complex/server
      - run: docker build -t devaprakash/multi-worker ./complex/worker/Dockerfile ./complex/worker
      - run: docker push devaprakash/multi-client
      - run: docker push devaprakash/multi-nginx
      - run: docker push devaprakash/multi-server
      - run: docker push devaprakash/multi-worker
